### ISSUE TITLE
Test fails, cannot find tallsorts.pkl.gz

### ISSUE THREAD

**Issue by tirohia** [Oshlack/TALLSorts#2]
A heads up, rather than an ongoing problem. i.e. this can be closed this whenever, I've got it working. 

It might have been system specific, i.e. my machine, but the install process didn't copy tallsorts.pkl.gz to the environment folder.

Solved by creating models/tallsorts/ in tallsortsenv/lib/python3.10/sitepackages/TALLSorts/ and copying the tallsorts.pkl.gz into that directory. 

Cheers
Ben.

**Comment by AllenZPGu** [comment]
Hi Ben, thanks for the issue and sorry for the long response time. It does seem to be a system-dependent issue. What is the system you're uisng? The setup seems to go fine on Mac and Windows. The manual copy should hold for now, until I can properly fix this (seems to be an issue with the `setup.py` file)
